# Generated by Django 3.0.4 on 2020-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='spentAmount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
