# Generated by Django 3.0.4 on 2020-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_report_spentamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='spentAmount',
            field=models.IntegerField(null=True),
        ),
    ]
