# Generated by Django 3.0.4 on 2020-03-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200323_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='spentAmount',
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summaryAmount',
            field=models.IntegerField(null=True),
        ),
    ]
