# Generated by Django 3.0.4 on 2020-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200324_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='maxAmount',
            field=models.IntegerField(null=True),
        ),
    ]
