# Generated by Django 3.0.4 on 2020-03-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200324_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.BooleanField(null=True)),
                ('summaryAmount', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summaryAmount',
        ),
    ]
