# Generated by Django 3.0.4 on 2020-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200324_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='maxAmount',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
